/*
 * CheckSumServer.h
 *
 *  Created on: Dec 13, 2015
 *      Author: onega
 */

#ifndef CHECKSUMSERVER_H_
#define CHECKSUMSERVER_H_
// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "CheckSumService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::htmltest;
namespace htmltest {
class CheckSumServer : virtual public CheckSumServiceIf {
 public:
	CheckSumServer() ;
	~CheckSumServer();
  void checksum(CheckSumResult& _return, const std::string& srcfilename) override;

  int32_t duplicated(const std::string& input_checksum) override;

  void addfolder(const std::string& pathname) override;

  void getprogress(CheckSumProgress& _return) override;

  void ping() override;

  void shutdown(const std::string& msg) override;
  void setserver(class TSimpleServer* server);
 private:
  class TSimpleServer* server_;
};

}

#endif /* CHECKSUMSERVER_H_ */
